= git-publish
:link-github: https://github.com/Rex--/git-publish/tree/dev
:link-docs: https://rex.mckinnon.ninja/git-publish-dev

Publish to remote directories using `git` + `ssh`.

WARNING: This document is currently a WIP - the information presented may not
be accurate.

== Quickstart

. Initialize a _publish repository_. This creates a bare repository on `server`
at `remote_path` and clones it to `local_path` (default `./<remote_name>`).

 $ git publish init <server>:<remote_path> [local_path]


. Add a _publish worktree_. This creates a directory on the publish
server (default `origin`) that will stay in sync with a branch (default `master`).

 $ git publish worktree <remote_path>


. Edit files, and push to a publish server (default `origin`). An optional
commit message can be used instead of the default. A custom commit message has
to be set only once, as if no message is given the last commit message is used.

 $ touch index.html
 $ git publish [-m "Custom Message"]


== Setup

=== Installing git-publish
To install the `git publish` command, simply place the script somewhere it is
available on your $PATH and mark it executable.

 $ cp git-publish ~/.local/bin
 $ chmod a+x ~/.local/bin/git-publish

Alternatively to stay up-to-date with the latest release, link directly to the git repository. It's recommended to checkout a tag or a commit in this case.

.The following example has not been tested
 $ git checkout --detach master
 $ ln -s git-publish ~/.local/bin
 $ chmod a+x git-publish



=== Linux File Permissions
The ssh user that you use to connect with git needs to have write permissions
to both the bare repository and the publish directory. An example setup is
a `publish` group that has *rwx* permissions to each parent directory:

 # mkdir /srv/git /srv/publish
 # groupadd publish
 # chgrp publish /srv/git /srv/publish
 # chmod g+w /srv/git /srv/publish
 # usermod -aG publish git

This will give the `git` user appropriate permissions to push to a repository
at `<server>:/srv/git/example.git` and publish files in `/srv/publish/example`.
Additional users can be granted permissions by adding them to the `publish` 
group.


== Usage
The basic workflow this suits is to keep a remote directory in sync with
one on your local machine. It achieves this by pushing a local repository to a
remote repository over ssh. This means an intermediate git host such as Github
is not required. A server hook that fires after a successful push is used to
trigger a force checkout of the main branch in a separate worktree on  the
remote server. This worktree is the directory that is kept in sync with the
local repo.

=== Initialize Publish Repository
When you initialize a repository with the `git publish init` command, it does
two main things:

1. Creates a bare repository on the given host and installs a post-receive hook.
2. Initializes a local repository and adds the remote as origin.

Let's initialize a publish repository on `example.com`. We'll call it `website`.

.Initializing a publish repository
====
 $ git publish init example.com:/git/website.git
 Connecting to server: example.com
 Repo: /git/website.git
 user@example.com's password: 
 Initialized empty Git repository in /git/website.git/
 Find this repo at: example.com:/git/website.git
 Cloning into local directory: website/
 Initialized empty Git repository in /home/user/website/.git/
====

=== Add Publish Directory

.Add a publish worktree
====
 $ git publish worktree /www/example.com
 Using remote 'origin' @ example.com:/git/website.git
 Creating publish worktree: /www/example.com
 user@example.com's password: 
 Preparing worktree (detached HEAD cf7f00d)
 HEAD is now at cf7f00d Publish Version 0
 Successfully created worktree: /www/example.com
====

=== Publish Files to Worktrees

====
 $ git publish
 Publishing repository: /home/user/website
 Using last commit message: Publish Version 0
 Incrementing commit version: 0 + 1
 [master 3e9a0d8] Publish Version 1
  1 file changed, 0 insertions(+), 0 deletions(-)
  create mode 100644 index.html
 user@example.com's password: 
 Enumerating objects: 3, done.
 Counting objects: 100% (3/3), done.
 Delta compression using up to 4 threads
 Compressing objects: 100% (2/2), done.
 Writing objects: 100% (2/2), 259 bytes | 259.00 KiB/s, done.
 Total 2 (delta 0), reused 0 (delta 0), pack-reused 0
 remote: Updating worktree: /www/example.com
 remote: HEAD is now at 3e9a0d8 Publish Version 1
 To localhost:/git/website.git
    cf7f00d..3e9a0d8  master -> master
 Published Version: 1
====






== Reference

[.big]#`git publish [init|worktree] [-d] [-r remote] [-b branch] [-m message] [files|server:remote_path|remote_path] [local_path]`#::
All commands accept some common configuration options in case you'd like to
change the defaults. All dashed arguments should come *before* any positional
arguments and *after* the subcommand.

[horizontal]
    `-r remote`::: The name of the remote to perform the publish operation on.
    (Default `origin`)
    `-b branch`::: The name of the branch to perform the operation on.
    (Default `master` or `init.defaultBranch` if set)

//-

[.big]#`git publish [-r] [-b] [-m message] [files]`#::
Publish files to a remote server. When run with no arguments, this publishes
all files in the directory to `origin/master`. Any worktrees that have been
created on `origin` will be updated.

[horizontal]
    `files`::: List of files to publish. (Default: `-A`)
    `-m message`::: Commit message to use. If no version is found in the
    message, one will be appended to the end. (Default: Last commit if exists,
    else "Publish Version")

//-

[.big]#`git publish init [-r] [-b] server:remote_path [local_path]`#::
Initialize a repository on the `server` at `remote_path` and link it with
`local_path`.

[horizontal]
    `server`::: Remote server uri. Accepts `[user@]host` and
    `ssh://[user@]host[:port]` formats.
    `remote_path`::: Path of the bare git repository on `server`.
    e.g. `/git/something-like.git`
    `[local_path]`::: Optional path to the local repository. (Default: Create a
    directory with the remote repository's name e.g. `./something-like/`)

//-

[.big]#`git publish worktree [-r] [-b] [-d] remote_path`#::
Create a new worktree at `remote_path` that gets updated on every push.

[horizontal]
    `remote_path`::: Path of new worktree on the remote.
    `-d`::: Delete `remote_path` instead of creating it.

---
[.text-center]
[.big]#{link-github}[github] | {link-docs}[documentation]# +
&copy; 2022 Rex McKinnon