= git-publish documentation
:link-github: https://github.com/Rex--/git-publish/tree/dev
:link-docs: https://rex.mckinnon.ninja/git-publish-dev
:link-docs-og: https://rex.mckinnon.ninja/git-publish
:icons: font
:toc: left

Publish to remote directories using `git` + `ssh`.

WARNING: This document is currently a WIP - the information presented may not
be accurate.

NOTE: This documentation is for the development version. It is functional, but
has not been tested very hard. Checkout the original version {link-docs-og}[here.]

== Quickstart

. **Init**ialize a _publish repository_. This creates a bare repository on `host`
at `remote_path` and clones it to `local_path` (default `./<remote_name>`).

 $ git publish init <host>:<remote_path> [local_path]


. Edit files, and *_publish_* to a remote repository (default `origin`). An optional
commit message can be used instead of the default. A custom commit message has
to be set only once, as if no message is given the last commit message is used
with an incremented version number.

 $ touch index.html
 $ git publish [-m "Custom Message"]


. Add a _publish **worktree**_. This creates a directory on the publish
server (default `origin`) that will stay in sync with a branch (default `master`
or `init.defaultBranch` if set).

 $ git publish worktree <remote_path> [local_path]

NOTE: Currently you cannot create any publish worktrees until you have pushed
at least one commit.



== Setup
Currently, `git-publish` and it's required programs have to be installed
manually.

=== Requirements
A few common programs are required to use `git-publish`. They can typically be
installed with your distro's package manager.

`git`::
git is required for, well, the `git` command. It's required to be installed on
both your local machine and the remote server.

`ssh`::
ssh is required for running commands on the remote server and pulling from git
repositories. It will also need to be installed on both the local machine and
the remote server. The remote server should be running an ssh server that is
accessible from the local machine.

`bash`::
Currently, the `git-publish` script uses a few "bashism"s, it is not guaranteed
to run in other shells. Because of this, `bash` is listed as a requirement,
however it may work in others.

=== Installing git-publish
To install the `git publish` command, simply place the script somewhere it is
available on your $PATH and mark it executable.

 $ cp git-publish ~/.local/bin
 $ chmod a+x ~/.local/bin/git-publish

Alternatively to stay up-to-date with the latest release, link directly to the
git repository. It's recommended to checkout a tag or a commit in this case.

.The following has not been testedw
 $ git checkout --detach master
 $ ln -s git-publish ~/.local/bin
 $ chmod a+x git-publish


=== Additional Considerations

==== &#46;git
Because we create a linked worktree to an existing repo, `.git` is a file
that contains a path to the common repo. This might expose sensitive
information e.g. if serving the directory with a web server. An example `.git`
created with the publish command contains the following:

 gitdir: /git/example.git/worktrees/example.com


==== Linux File Permissions
The ssh user that you use to connect with git needs to have write permissions
to both the bare repository and the publish directory. An example setup is
a `publish` group that has *rwx* permissions to each parent directory.
The example below will give the `git` user appropriate permissions to push to a
repository at `<server>:/srv/git/example.git` and publish files in
`/srv/publish/example`. Additional users can be granted permissions by adding
them to the `publish` group.

 # mkdir /srv/git /srv/publish
 # groupadd publish
 # chgrp publish /srv/git /srv/publish
 # chmod g+w /srv/git /srv/publish
 # usermod -aG publish git

Alternatively, you could just work in the user's home directory:

 $ mkdir ~/git ~/publish

NOTE: `git publish` requires absolute paths for all arguments that take a path.


==== SSH Host
The publish server is required to be accessible over ssh. This means we have to
authenticate with it somehow, however, most of the time it is recommend to
disable password logins for security. The easiest way to authenticate using a
key pair is by installing the needed key to your `ssh-agent`. This also means
you won't have to type in any passwords to login to the publish server.

Sometimes, you may not have an ssh-agent running or maybe you are running the
server on a non-standard port. These situations require you to configure the
ssh connection. The current recommended way to do this is by editing
`~/.ssh/config` and configuring a custom hostname for your ssh server. An
example of one such host is given below:

 Host <custom-host>
     Hostname       <ip>
     Port           <port>
     User           <user>
     IdentityFile   <path/to/private_key>

All configuration options are optional, just use what you need to change from
the defaults. You can now use `<custom-host>` as a hostname like:

 git publish init <custom-host>:/path/to/repo.git


== Usage
The basic workflow this suits is to keep a remote directory in sync with
one on your local machine. It achieves this by pushing a local repository to a
remote repository over ssh. This means an intermediate git host such as Github
is not required. A git server hook that fires after a successful push is used
to trigger a force checkout of the main branch for every published worktree
on the server. These worktree directories contain a copy of the latest
committed files.

=== Initialize Publish Repository
When you initialize a repository with the `git publish init` command, it does
two main things:

1. Creates a bare repository on the given host and installs a post-receive hook.
2. Initializes a local repository and adds the remote as origin.

Let's initialize a publish repository on `example.com`. We'll call it `website`.

.Initializing a publish repository
====
 $ git publish init example.com:/git/website.git
 Connecting to server: example.com
 Repo: /git/website.git
 user@example.com's password: 
 Initialized empty Git repository in /git/website.git/
 Find this repo at: example.com:/git/website.git
 Cloning into local directory: website/
 Initialized empty Git repository in /home/user/website/.git/
====

This created two repositories: `/git/website.git` on our server and
`website/.git` on our local machine.

Inside of our local repo, if we run `git remote get-url origin` (or whatever
you set the remote to be) we can see it is set up to push/pull from
`example.com:/git/website.git`. The git-publish command just runs a `git init`
and then `git remote add` to setup the local repository.

In our server repo, the only interesting thing you will find is a shell script
`post-receive` that gets installed in `<repo>/hooks/` --
`example.git/hooks/post-receive` in the case of the example above. This script,
which runs after a successful push, simply finds all *.publish files in the
hooks/ directory and executes them. Other than this simple one-line script, the
bare repository is bog standard.

=== Add Publish Directory

.Add a publish worktree
====
 $ git publish worktree /www/example.com
 Using remote 'origin' @ example.com:/git/website.git
 Creating publish worktree: /www/example.com
 user@example.com's password: 
 Preparing worktree (detached HEAD cf7f00d)
 HEAD is now at cf7f00d Publish Version 0
 Successfully created worktree: /www/example.com
====

=== Publish Files to Worktrees

.Publish a repository
====
 $ git publish
 Publishing repository: /home/user/website
 Using last commit message: Publish Version 0
 Incrementing commit version: 0 + 1
 [master 3e9a0d8] Publish Version 1
  1 file changed, 0 insertions(+), 0 deletions(-)
  create mode 100644 index.html
 user@example.com's password: 
 Enumerating objects: 3, done.
 Counting objects: 100% (3/3), done.
 Delta compression using up to 4 threads
 Compressing objects: 100% (2/2), done.
 Writing objects: 100% (2/2), 259 bytes | 259.00 KiB/s, done.
 Total 2 (delta 0), reused 0 (delta 0), pack-reused 0
 remote: Updating worktree: /www/example.com
 remote: HEAD is now at 3e9a0d8 Publish Version 1
 To example.com:/git/website.git
    cf7f00d..3e9a0d8  master -> master
 Published Version: 1
====



// == git-publish(1)
include::git-publish-man.adoc[leveloffset=+1]



---
[.text-center]
[.big]#{link-github}[github] | {link-docs}[documentation]# +
&copy; 2022 Rex McKinnon
